version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /style\.css
  static_files: style.css
  upload: style\.css

- url: /stylesheets
  static_dir: stylesheets

- url: /.*
  script: main.app

libraries:
- name: jinja2
  version: latest
